table 'SFX vw_SubFiles_Operations'
	lineageTag: 53edcb80-9f00-4c14-97f0-daf52bc9677b

	column 'Operation Item ID'
		dataType: string
		lineageTag: 413096ba-25b9-4e1c-b047-2b6912a76df7
		summarizeBy: none
		sourceColumn: Operation Item ID

		annotation SummarizationSetBy = Automatic

	column 'Operation Item Name'
		dataType: string
		lineageTag: c0ab7714-8bbb-411f-85e3-4e44cb64ee87
		summarizeBy: none
		sourceColumn: Operation Item Name

		annotation SummarizationSetBy = Automatic

	column 'Operation Qty'
		dataType: double
		lineageTag: 36da8745-6617-4c91-92b5-db2d86a520af
		summarizeBy: sum
		sourceColumn: Operation Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Request Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 94afb76b-3380-4b9d-924d-0f512383e31e
		summarizeBy: none
		sourceColumn: Request Date

		variation Variation
			isDefault
			relationship: 622757dc-6f55-42ee-81f7-008c1fd8d19b
			defaultHierarchy: LocalDateTable_3dbcaf63-a1d3-4848-827b-daddb05dcd00.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column 'Operation Status Name'
		dataType: string
		lineageTag: 23d9d2a1-6612-4fc9-8027-50f1822280a6
		summarizeBy: none
		sourceColumn: Operation Status Name

		annotation SummarizationSetBy = Automatic

	column SubFile
		dataType: string
		lineageTag: fc105b62-ff98-434e-8e22-cfc9b1c3c1fc
		summarizeBy: none
		sourceColumn: SubFile

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: c18346bc-3879-49d4-90cc-e016d619194d
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Operation Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 747c58de-7654-42fa-a247-3bb18f597e49
		summarizeBy: none
		sourceColumn: Operation Date

		variation Variation
			isDefault
			relationship: 668b654c-2af7-44f2-a6fd-06e752e28ab2
			defaultHierarchy: LocalDateTable_4aeb279c-3d66-4779-a837-dc76217d61e9.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column 'Operation Closing Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: c74efba6-3618-4804-8bfa-a348480ee175
		summarizeBy: none
		sourceColumn: Operation Closing Date

		variation Variation
			isDefault
			relationship: 17870e2c-e836-473e-8595-b65f521206b7
			defaultHierarchy: LocalDateTable_54df0c4d-e928-4c8e-8aea-9afab295cb64.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 88fa1978-412c-43cf-970d-fcf1490d196d
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 41a7d006-58ab-4e25-947a-1d76a6b01842
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Customer Locality'
		dataType: string
		lineageTag: 885ce2a1-2ae7-4f8d-ae34-f29a5d967bc0
		summarizeBy: none
		sourceColumn: Customer Locality

		annotation SummarizationSetBy = Automatic

	column 'Customer Country ID'
		dataType: string
		lineageTag: cda04bed-0e85-43cb-ac4c-c7a0f5f54e2e
		summarizeBy: none
		sourceColumn: Customer Country ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Country Name'
		dataType: string
		lineageTag: 4ebce994-9ffc-4bc5-88fd-eb13fac56b52
		summarizeBy: none
		sourceColumn: Customer Country Name

		annotation SummarizationSetBy = Automatic

	column 'Customer CO'
		dataType: string
		lineageTag: b53b7328-f97c-408b-b2c8-52421ab2b09f
		summarizeBy: none
		sourceColumn: Customer CO

		annotation SummarizationSetBy = Automatic

	column 'File No'
		dataType: string
		lineageTag: c5510f7b-e716-4be9-a5fd-fb44939d6c68
		summarizeBy: none
		sourceColumn: File No

		annotation SummarizationSetBy = Automatic

	column 'File Period'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 862b496b-244b-4d83-9de2-1b01f891f2ed
		summarizeBy: none
		sourceColumn: File Period

		variation Variation
			isDefault
			relationship: e864e629-cdbb-4691-bbd8-b9db81232483
			defaultHierarchy: LocalDateTable_fe0d4507-5024-4ab4-bf8a-44a3a713cbb2.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Opening Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fefae6d3-2202-4477-b537-90b67c48d690
		summarizeBy: none
		sourceColumn: Opening Date

		variation Variation
			isDefault
			relationship: 1fcfae76-3c97-4884-9f39-c6a7725c4322
			defaultHierarchy: LocalDateTable_83793daf-614d-44b4-9b99-5929292b0e8b.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Closing Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3ed137f1-15e7-4e8f-adb1-0e5fa3aea211
		summarizeBy: none
		sourceColumn: Closing Date

		variation Variation
			isDefault
			relationship: bc6bc856-20b2-4964-9a4d-7ee9404a332b
			defaultHierarchy: LocalDateTable_9d9523cc-8be0-45ec-8607-971f640990b4.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Is Excluded Statistic'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 09bc70fe-dfab-441d-a230-628c72d449be
		summarizeBy: none
		sourceColumn: Is Excluded Statistic

		annotation SummarizationSetBy = Automatic

	column 'Customer Ref'
		dataType: string
		lineageTag: dec38ff2-ec5e-441d-ae66-7abb85e4293e
		summarizeBy: none
		sourceColumn: Customer Ref

		annotation SummarizationSetBy = Automatic

	column 'Master Customer ID'
		dataType: string
		lineageTag: 1b01980e-d885-42f9-b0ea-0b4296b594d9
		summarizeBy: none
		sourceColumn: Master Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Master Customer Name'
		dataType: string
		lineageTag: c0b071dc-f139-4b26-a229-9c83127caea6
		summarizeBy: none
		sourceColumn: Master Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Master Customer Locality'
		dataType: string
		lineageTag: 819aae42-632a-4d10-a7bb-87d132364c31
		summarizeBy: none
		sourceColumn: Master Customer Locality

		annotation SummarizationSetBy = Automatic

	column 'Master Customer Country ID'
		dataType: string
		lineageTag: 84ec53cd-10fc-4880-ac12-15fe71158f12
		summarizeBy: none
		sourceColumn: Master Customer Country ID

		annotation SummarizationSetBy = Automatic

	column 'Master Customer Country Name'
		dataType: string
		lineageTag: 18aa6ae6-5716-4e7d-b1d5-fb2b23d78bde
		summarizeBy: none
		sourceColumn: Master Customer Country Name

		annotation SummarizationSetBy = Automatic

	column 'Customer Group ID'
		dataType: string
		lineageTag: 64542fc9-96e7-4ee5-8387-b970aa0278f8
		summarizeBy: none
		sourceColumn: Customer Group ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Group Name'
		dataType: string
		lineageTag: 8b2e187b-c77c-448d-b5ad-242593917ec9
		summarizeBy: none
		sourceColumn: Customer Group Name

		annotation SummarizationSetBy = Automatic

	column 'File Type ID'
		dataType: string
		lineageTag: ce120e9d-a083-4b5f-b3ca-40bfdb466e31
		summarizeBy: none
		sourceColumn: File Type ID

		annotation SummarizationSetBy = Automatic

	column 'File Type Name'
		dataType: string
		lineageTag: ec0a19df-55ee-4341-bc29-e3386a0ee758
		summarizeBy: none
		sourceColumn: File Type Name

		annotation SummarizationSetBy = Automatic

	column 'Traffic ID'
		dataType: string
		lineageTag: a48366b8-5eea-4ba5-9452-f064f18bb392
		summarizeBy: none
		sourceColumn: Traffic ID

		annotation SummarizationSetBy = Automatic

	column 'Traffic Name'
		dataType: string
		lineageTag: 0baaa639-9b17-4ee5-b5a8-c3ebd0931b5d
		summarizeBy: none
		sourceColumn: Traffic Name

		annotation SummarizationSetBy = Automatic

	column 'Transport Mode ID'
		dataType: string
		lineageTag: 540f3b76-b65e-48ef-89a8-2c25ca416b95
		summarizeBy: none
		sourceColumn: Transport Mode ID

		annotation SummarizationSetBy = Automatic

	column 'Transport Mode Name'
		dataType: string
		lineageTag: f7b8cac4-87e0-4cef-8d29-1992cba7c1b5
		summarizeBy: none
		sourceColumn: Transport Mode Name

		annotation SummarizationSetBy = Automatic

	column 'Activity ID'
		dataType: string
		lineageTag: 56277530-332f-4f3c-98e5-17ad2f15251a
		summarizeBy: none
		sourceColumn: Activity ID

		annotation SummarizationSetBy = Automatic

	column 'Activity Name'
		dataType: string
		lineageTag: 50a6f16e-a818-4bf0-881c-acca0e5ba423
		summarizeBy: none
		sourceColumn: Activity Name

		annotation SummarizationSetBy = Automatic

	column 'Module ID'
		dataType: string
		lineageTag: 1184fcd9-b9e4-492d-ba5b-5f48b0353eb1
		summarizeBy: none
		sourceColumn: Module ID

		annotation SummarizationSetBy = Automatic

	column 'Module Name'
		dataType: string
		lineageTag: 6cf83eef-c8c1-43c5-9ea0-1d463526e17c
		summarizeBy: none
		sourceColumn: Module Name

		annotation SummarizationSetBy = Automatic

	column 'Division ID'
		dataType: string
		lineageTag: 13ab1860-c2c2-46b9-a980-5d3041d5a76a
		summarizeBy: none
		sourceColumn: Division ID

		annotation SummarizationSetBy = Automatic

	column 'Division Name'
		dataType: string
		lineageTag: fb9697b4-bef3-4a9f-a402-cefb32337639
		summarizeBy: none
		sourceColumn: Division Name

		annotation SummarizationSetBy = Automatic

	column 'Is Warehousing'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 648a43c1-7d21-4e5d-9b34-2c72b3c7dbcd
		summarizeBy: none
		sourceColumn: Is Warehousing

		annotation SummarizationSetBy = Automatic

	column 'Client Network'
		dataType: string
		lineageTag: e8359f98-397f-40b0-819a-335441fee9f8
		summarizeBy: none
		sourceColumn: Client Network

		annotation SummarizationSetBy = Automatic

	column 'Shipping Line'
		dataType: string
		lineageTag: e5e37429-ffb3-45f5-9a12-6a18aa1f5371
		summarizeBy: none
		sourceColumn: Shipping Line

		annotation SummarizationSetBy = Automatic

	column Airline
		dataType: string
		lineageTag: 6ee3c188-aa86-4b2f-8a52-09cca580f952
		summarizeBy: none
		sourceColumn: Airline

		annotation SummarizationSetBy = Automatic

	column 'File Numbering ID'
		dataType: string
		lineageTag: 80b69de6-4be3-49fd-bf10-ca9a212bda9b
		summarizeBy: none
		sourceColumn: File Numbering ID

		annotation SummarizationSetBy = Automatic

	column 'Complements Text'
		dataType: string
		lineageTag: b7b10414-61a6-46e1-8694-c45d7c6da604
		summarizeBy: none
		sourceColumn: Complements Text

		annotation SummarizationSetBy = Automatic

	column 'Module Profile'
		dataType: int64
		formatString: 0
		lineageTag: e4437ab5-8dc2-4b81-a34b-612fd6d9f10a
		summarizeBy: sum
		sourceColumn: Module Profile

		annotation SummarizationSetBy = Automatic

	column 'File Status ID'
		dataType: string
		lineageTag: 9df763f4-6d1d-481a-b66a-fbc4b3441556
		summarizeBy: none
		sourceColumn: File Status ID

		annotation SummarizationSetBy = Automatic

	column 'File Status Name'
		dataType: string
		lineageTag: 18f47d0e-15d1-4d16-9470-f49d93601531
		summarizeBy: none
		sourceColumn: File Status Name

		annotation SummarizationSetBy = Automatic

	column 'File Status Index'
		dataType: int64
		formatString: 0
		lineageTag: 381ffd04-414a-46eb-ab50-884afcc4e69c
		summarizeBy: sum
		sourceColumn: File Status Index

		annotation SummarizationSetBy = Automatic

	partition 'SFX vw_SubFiles_Operations' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("SFX-HP-01"),
				    BopxCWE = Source{[Name="BrainOpxOMAGH0"]}[Data],
				    SFX_vw_SubFiles_Operations = BopxCWE{[Schema="SFX",Item="vw_SubFiles_Operations"]}[Data],
				    #"Colonnes supprimées" = Table.RemoveColumns(SFX_vw_SubFiles_Operations,{"Reference ID", "Reference Name", "Operation Grouping", "Row ID", "Agency ID", "Agency Name", "Agency Branch", "Branch Mapping", "Agency Group Id", "Agency Group Name", "Estimation Date", "Completing Date", "Operation Duration", "Estimate Completing Time", "Delay Duration", "Responsible ID", "Responsible Name", "Observation", "Operation Status ID", "Operation ID"})
				in
				    #"Colonnes supprimées"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

