table tq_Statuts_Operation
	lineageTag: a3967c46-60a0-4f9c-9f99-9ed6ef42fd92

	column 'Code Liste'
		dataType: string
		lineageTag: e6b14934-4e8c-4b7d-becc-8f04fa94d244
		summarizeBy: none
		sourceColumn: Code Liste

		annotation SummarizationSetBy = Automatic

	column Valeur
		dataType: string
		lineageTag: b5177b05-b4f2-4a90-8d56-0bb0bdc3d136
		summarizeBy: none
		sourceColumn: Valeur

		annotation SummarizationSetBy = Automatic

	column 'Libelle Liste'
		dataType: string
		lineageTag: da551629-e825-432f-9bf3-cc715d935bbc
		summarizeBy: none
		sourceColumn: Libelle Liste

		annotation SummarizationSetBy = Automatic

	partition tq_Statuts_Operation = m
		mode: import
		source =
				let
				    Source = Sql.Databases("SFX-HP-01"),
				    BopxCWE = Source{[Name="BrainOpxOMAGH0"]}[Data],
				    dbo_tq_Statuts_Operation = BopxCWE{[Schema="dbo",Item="tq_Statuts_Operation"]}[Data],
				    #"Type modifié" = Table.TransformColumnTypes(dbo_tq_Statuts_Operation,{{"Valeur", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

